[package]
name = "ROVer"
version = "0.1.1"
edition = "2018"
authors = ["The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>"]
description = "An RPKI Discord bot."
repository = "https://github.com/NLnetLabs/ROVer"
keywords = ["rpki", "routing-security", "bgp"]
categories = ["command-line-utilities"]
license = "BSD-3-Clause"
readme = "README.md"

[[bin]]
name = "rover"
path = "src/main.rs"

[dependencies]
serde = "*"

[dependencies.serenity]
version = "0.10"

[dependencies.tokio]
features = ["macros", "rt-multi-thread"]
version = "1.0"

[dependencies.ureq]
features = ["json"]
version = "2.1.0"

[dev-dependencies]
serde_json = "1.0"

[package.metadata.deb]
name = "rover"
maintainer = "The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>"
license-file = ["LICENSE", "0"]
extended-description = """\
A Discord bot that fetches and displays the RPKI validity of a route."""
depends = "$auto, adduser"
section = "net"
priority = "optional"
assets = [
    ["target/release/rover", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/rover/", "644"],
    ["doc/rover.1", "usr/share/man/man1/rover.1", "644"],
    ["debian/service.preset", "/lib/systemd/system-preset/50-rover.preset", "644"],
]
maintainer-scripts = "debian"
changelog = "debian/changelog" # this will be generated by the pkg workflow
copyright = "Copyright (c) 2021, NLnet Labs. All rights reserved."
systemd-units = { unit-name = "rover", enable = false }

[package.metadata.deb.variants.minimal]