.TH "rover" "1" "NLnet Labs"
.SH NAME
rover - RPKI Discord bot
.SH SYNOPSIS
rover -h, --help

rover -V, --version
.SH DESCRIPTION
ROVer is a Discord bot that fetches and displays the RPKI validity of a route
This manual page documents the krill daemon.

For more information please see:
    https://github.com/NLnetLabs/ROVer/

.SH OPTIONS
The available options are:

.TP
.BI -h,\ --help
Prints help information.

.TP
.BI -V,\ --version
Prints version information.