#!/bin/sh -e

ROVER_HOME="/var/lib/rover/"
ROVER_USER="rover"

create_user() {
    if id ${ROVER_USER} > /dev/null 2>&1; then return; fi
    adduser --system --home "${ROVER_HOME}" --group ${ROVER_USER}
}

case "$1" in
configure)
    create_user
    ;;
esac

#DEBHELPER#